title: 陆国松的编程笔记
email: luguosong8@163.com
#description: >- # this means to ignore newlines until "baseurl:"
#  编程学习笔记
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "许可证："

#回到顶部
back_to_top: true
back_to_top_text: 回到顶部⬆

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "在Github中编辑此页面."
gh_edit_repository: "https://github.com/guosonglu/code-notes" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# 这个使用的是小号，大号可能有安全隐患
gitment_owner: luguosong
gitment_repo: luguosong.github.io
gitment_oauth:
  client_id: 0d8aaec11145d797cdfa
  client_secret: 43cec67aeda473d51e3975f5f9ea4b2d60fb1cb3

# Build settings
theme: "just-the-docs"
color_scheme: dark
plugins:
  - jekyll-feed


collections:
  general:
    output: true
  java:
    output: true
  c:
    output: true
  math:
    output: true
  environment:
    output: true


just_the_docs:
  collections:
    general:
      name: 编程基础
    java:
      name: Java
    c:
      name: C
    math:
      name: 数学
    environment:
      name: 环境与配置


aux_links:
  "code-notes on GitHub":
    - "//github.com/guosonglu/code-notes"
