title: 陆国松的编程笔记
email: luguosong8@163.com
#description: >- # this means to ignore newlines until "baseurl:"
#  编程学习笔记
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

# Build settings
theme: "just-the-docs"
color_scheme: dark
plugins:
  - jekyll-feed

#默认配置
#defaults:
#  - scope: #范围
#      path: ""  #路径匹配
#    values:  #YAML 头信息
#      layout: "default"


## 目录结构
#source:      .
#destination: ./_site
#plugins:     ./_plugins
#layouts:     ./_layouts
#data_source: ./_data
collections:
  java:
    output: true
  c:
    output: true

just_the_docs:
  collections:
    java:
      name: Java
    c:
      name: C

## 阅读处理
#safe:         false
#include:      [".htaccess"]
#exclude:      []
#keep_files:   [".git", ".svn"]
#encoding:     "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## 内容过滤
#show_drafts: null
#limit_posts: 0
#future:      true
#unpublished: false

## 插件
#whitelist: []
#gems:      []

## 转换
#markdown:    kramdown
#highlighter: rouge
#lsi:         false
#excerpt_separator: "\n\n"
#incremental: false

## 服务器选项
#detach:  false
#port:    4000
#host:    127.0.0.1
#baseurl: "" # does not include hostname

## 输出
#permalink:     date
#paginate_path: /page:num
#timezone:      null

#quiet:    false
#defaults: []

## Markdown 处理器
#rdiscount:
#  extensions: []

#redcarpet:
#  extensions: []

#kramdown:
#  auto_ids:       true
#  footnote_nr:    1
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false

#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style

aux_links:
  "code-notes on GitHub":
    - "//github.com/guosonglu/code-notes"
