server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id：router1 #路由标识，必须唯一
          uri: lb://client-gateway-user #路由的目标地址
          predicates:
            - Path=/user/** # 路径断言，判断路径是否是以/user开头
        - id：router2 #路由标识，必须唯一
          uri: lb://client-gateway-order #路由的目标地址
          predicates:
            - Path=/order/** # 路径断言，判断路径是否是以/user开头


