server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: client-gateway-user #指定服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis:
  type-aliases-package: com.luguosong.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.luguosong: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

